services:
  grafana:
    user: root
    container_name: 'hydrolix-datasource'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.0.2}
        #grafana_version: ${GRAFANA_VERSION:-11.5.4}
        #grafana_version: ${GRAFANA_VERSION:-10.4.16}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../dist:/var/lib/grafana/plugins/hydrolix-datasource
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/hydrolix-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.hydrolix-hydrolix-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: hydrolix-hydrolix-datasource
